namespace SpriteKind {
    export const boss = SpriteKind.create()
}
sprites.onDestroyed(SpriteKind.boss, function (sprite) {
    game.gameOver(true)
    pause(2000)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    music.stopAllSounds()
    game.setGameOverMessage(false, "ざこおつ")
    game.gameOver(false)
})
scene.onOverlapTile(SpriteKind.Player, tiles.util.arrow1, function (sprite, location) {
    tiles.setTileAt(location, sprites.dungeon.collectibleRedCrystal)
    music.play(music.melodyPlayable(music.smallCrash), music.PlaybackMode.InBackground)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    controller.moveSprite(mySprite, 120, 120)
})
scene.onOverlapTile(SpriteKind.Player, tiles.util.arrow0, function (sprite, location) {
    tiles.setTileAt(location, sprites.dungeon.collectibleRedCrystal)
    music.play(music.melodyPlayable(music.smallCrash), music.PlaybackMode.InBackground)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile0`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`myTile2`)
    music.play(music.melodyPlayable(music.baDing), music.PlaybackMode.InBackground)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile5`, function (sprite, location) {
    music.stopAllSounds()
    sprites.destroy(mySprite2)
    sprites.destroy(_5)
    sprites.destroy(_6)
    tiles.setCurrentTilemap(tilemap`レベル5`)
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.collectibleRedCrystal)
    teki = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.boss)
    tiles.placeOnRandomTile(teki, sprites.dungeon.collectibleBlueCrystal)
    _２ = sprites.create(img`
        . . f f f . . . . . . . . f f f 
        . f f c c . . . . . . f c b b c 
        f f c c . . . . . . f c b b c . 
        f c f c . . . . . . f b c c c . 
        f f f c c . c c . f c b b c c . 
        f f c 3 c c 3 c c f b c b b c . 
        f f b 3 b c 3 b c f b c c b c . 
        . c b b b b b b c b b c c c . . 
        . c 1 b b b 1 b b c c c c . . . 
        c b b b b b b b b b c c . . . . 
        c b c b b b c b b b b f . . . . 
        f b 1 f f f 1 b b b b f c . . . 
        f b b b b b b b b b b f c c . . 
        . f b b b b b b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `, SpriteKind.boss)
    tiles.placeOnRandomTile(_２, sprites.dungeon.collectibleInsignia)
    _３ = sprites.create(img`
        ........................
        ........................
        ...........ccc..........
        ...........cccc.........
        .......ccc..ccccccc.....
        .......cccccc555555cc...
        ........ccb5555555555c..
        .....cc..b555555555555c.
        .....cccb555555ff155555c
        ......cb55555555ff55d55c
        ......b5555555555555555c
        ...cc.b555dd5555bb13bbc.
        ...cccd55ddddd555b3335c.
        .....bdddddddddd55b335c.
        ..cccdddddb55bbddd5555c.
        ..cccdddddb555bbbbcccc..
        ...ccddddddb5555cbcdc...
        ccccbdddddd5cb55cbcc....
        cddddddddd5555ccbbc.....
        .cddddddbdd555bbbcc.....
        ..ccdddbbbdd55cbcdc.....
        ....ccbbcbddddccdddcc...
        ......cccdd555dcccccc...
        ........cccccccc........
        `, SpriteKind.boss)
    tiles.placeOnRandomTile(_３, sprites.dungeon.hazardLava0)
    music.play(music.stringPlayable("E B C5 A B G A F ", 200), music.PlaybackMode.LoopingInBackground)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.boss, function (sprite, otherSprite) {
    music.stopAllSounds()
    game.setGameOverMessage(false, "ざこおつ")
    game.gameOver(false)
})
scene.onOverlapTile(SpriteKind.Player, tiles.util.arrow5, function (sprite, location) {
    tiles.setTileAt(location, sprites.dungeon.collectibleRedCrystal)
    music.play(music.melodyPlayable(music.smallCrash), music.PlaybackMode.InBackground)
})
scene.onOverlapTile(SpriteKind.Player, tiles.util.arrow4, function (sprite, location) {
    tiles.setTileAt(location, sprites.dungeon.collectibleRedCrystal)
    music.play(music.melodyPlayable(music.smallCrash), music.PlaybackMode.InBackground)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile1`, function (sprite, location) {
    tiles.setTileAt(location, assets.tile`myTile4`)
    music.play(music.melodyPlayable(music.baDing), music.PlaybackMode.InBackground)
})
let _３: Sprite = null
let _２: Sprite = null
let teki: Sprite = null
let _6: Sprite = null
let _5: Sprite = null
let mySprite2: Sprite = null
let mySprite: Sprite = null
tiles.setCurrentTilemap(tilemap`レベル2`)
mySprite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f e e e e f f . . . . 
    . . . f e e e f f e e e f . . . 
    . . f f f f f 2 2 f f f f f . . 
    . . f f e 2 e 2 2 e 2 e f f . . 
    . . f e 2 f 2 f f 2 f 2 e f . . 
    . . f f f 2 2 e e 2 2 f f f . . 
    . f f e f 2 f e e f 2 f e f f . 
    . f e e f f e e e e f e e e f . 
    . . f e e e e e e e e e e f . . 
    . . . f e e e e e e e e f . . . 
    . . e 4 f f f f f f f f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
scene.cameraFollowSprite(mySprite)
tiles.placeOnRandomTile(mySprite, sprites.castle.tileGrass2)
mySprite2 = sprites.create(img`
    . . . . c c c c c c . . . . . . 
    . . . c 6 7 7 7 7 6 c . . . . . 
    . . c 7 7 7 7 7 7 7 7 c . . . . 
    . c 6 7 7 7 7 7 7 7 7 6 c . . . 
    . c 7 c 6 6 6 6 c 7 7 7 c . . . 
    . f 7 6 f 6 6 f 6 7 7 7 f . . . 
    . f 7 7 7 7 7 7 7 7 7 7 f . . . 
    . . f 7 7 7 7 6 c 7 7 6 f c . . 
    . . . f c c c c 7 7 6 f 7 7 c . 
    . . c 7 2 7 7 7 6 c f 7 7 7 7 c 
    . c 7 7 2 7 7 c f c 6 7 7 6 c c 
    c 1 1 1 1 7 6 f c c 6 6 6 c . . 
    f 1 1 1 1 1 6 6 c 6 6 6 6 f . . 
    f 6 1 1 1 1 1 6 6 6 6 6 c f . . 
    . f 6 1 1 1 1 1 1 6 6 6 f . . . 
    . . c c c c c c c c c f . . . . 
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(mySprite2, sprites.castle.tileDarkGrass2)
_5 = sprites.create(img`
    . . . . c c c c c c . . . . . . 
    . . . c 6 7 7 7 7 6 c . . . . . 
    . . c 7 7 7 7 7 7 7 7 c . . . . 
    . c 6 7 7 7 7 7 7 7 7 6 c . . . 
    . c 7 c 6 6 6 6 c 7 7 7 c . . . 
    . f 7 6 f 6 6 f 6 7 7 7 f . . . 
    . f 7 7 7 7 7 7 7 7 7 7 f . . . 
    . . f 7 7 7 7 6 c 7 7 6 f c . . 
    . . . f c c c c 7 7 6 f 7 7 c . 
    . . c 7 2 7 7 7 6 c f 7 7 7 7 c 
    . c 7 7 2 7 7 c f c 6 7 7 6 c c 
    c 1 1 1 1 7 6 f c c 6 6 6 c . . 
    f 1 1 1 1 1 6 6 c 6 6 6 6 f . . 
    f 6 1 1 1 1 1 6 6 6 6 6 c f . . 
    . f 6 1 1 1 1 1 1 6 6 6 f . . . 
    . . c c c c c c c c c f . . . . 
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(_5, sprites.castle.tileDarkGrass2)
_6 = sprites.create(img`
    . . . . c c c c c c . . . . . . 
    . . . c 6 7 7 7 7 6 c . . . . . 
    . . c 7 7 7 7 7 7 7 7 c . . . . 
    . c 6 7 7 7 7 7 7 7 7 6 c . . . 
    . c 7 c 6 6 6 6 c 7 7 7 c . . . 
    . f 7 6 f 6 6 f 6 7 7 7 f . . . 
    . f 7 7 7 7 7 7 7 7 7 7 f . . . 
    . . f 7 7 7 7 6 c 7 7 6 f c . . 
    . . . f c c c c 7 7 6 f 7 7 c . 
    . . c 7 2 7 7 7 6 c f 7 7 7 7 c 
    . c 7 7 2 7 7 c f c 6 7 7 6 c c 
    c 1 1 1 1 7 6 f c c 6 6 6 c . . 
    f 1 1 1 1 1 6 6 c 6 6 6 6 f . . 
    f 6 1 1 1 1 1 6 6 6 6 6 c f . . 
    . f 6 1 1 1 1 1 1 6 6 6 f . . . 
    . . c c c c c c c c c f . . . . 
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(_6, sprites.castle.tileDarkGrass2)
teki = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Food)
_２ = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Food)
_３ = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Food)
music.play(music.stringPlayable("C D E F G A B C5 ", 120), music.PlaybackMode.LoopingInBackground)
forever(function () {
	
})
game.onUpdateInterval(500, function () {
    if (tiles.tileAtLocationEquals(tiles.getTileLocation(11, 6), assets.tile`myTile4`)) {
        if (tiles.tileAtLocationEquals(tiles.getTileLocation(4, 7), assets.tile`myTile2`)) {
            tiles.setTileAt(tiles.getTileLocation(0, 0), assets.tile`myTile5`)
        }
    }
})
game.onUpdateInterval(500, function () {
    if (tiles.tileAtLocationEquals(tiles.getTileLocation(2, 1), sprites.dungeon.collectibleRedCrystal)) {
        if (tiles.tileAtLocationEquals(tiles.getTileLocation(10, 6), sprites.dungeon.collectibleRedCrystal)) {
            if (tiles.tileAtLocationEquals(tiles.getTileLocation(2, 12), sprites.dungeon.collectibleRedCrystal)) {
                if (tiles.tileAtLocationEquals(tiles.getTileLocation(12, 12), sprites.dungeon.collectibleRedCrystal)) {
                    music.stopAllSounds()
                    tiles.placeOnTile(mySprite, tiles.getTileLocation(7, 8))
                    tiles.placeOnTile(teki, tiles.getTileLocation(7, 6))
                    tiles.placeOnTile(_２, tiles.getTileLocation(8, 6))
                    tiles.placeOnTile(_３, tiles.getTileLocation(6, 6))
                    tiles.setWallAt(mySprite.tilemapLocation(), true)
                    tiles.setWallAt(teki.tilemapLocation(), true)
                    tiles.setWallAt(_２.tilemapLocation(), true)
                    tiles.setWallAt(_３.tilemapLocation(), true)
                    controller.moveSprite(mySprite, 0, 0)
                    sprites.destroy(teki, effects.trail, 1000)
                }
            }
        }
    }
})
game.onUpdateInterval(500, function () {
    scene.followPath(mySprite2, scene.aStar(tiles.locationOfSprite(mySprite2), tiles.locationOfSprite(mySprite)), 80)
    scene.followPath(teki, scene.aStar(tiles.locationOfSprite(teki), tiles.locationOfSprite(mySprite)), randint(100, 180))
    scene.followPath(_２, scene.aStar(tiles.locationOfSprite(_２), tiles.locationOfSprite(mySprite)), randint(100, 180))
    scene.followPath(_３, scene.aStar(tiles.locationOfSprite(_３), tiles.locationOfSprite(mySprite)), randint(100, 180))
    scene.followPath(_5, scene.aStar(tiles.locationOfSprite(_5), tiles.locationOfSprite(mySprite)), 80)
    scene.followPath(_6, scene.aStar(tiles.locationOfSprite(_6), tiles.locationOfSprite(mySprite)), 80)
})
